
DROP TABLE SYS_SHEDLOCK_APP;
DROP TABLE SYS_SHEDLOCK_JOB;

-- 定时任务应用配置
CREATE TABLE SYS_SHEDLOCK_APP (
  APPLICATION VARCHAR2(64) NOT NULL ,
  HOST_IP VARCHAR2(32) not null,
  HOST_NAME VARCHAR2(100),
  STATE CHAR(1) DEFAULT 1,
  UPDATE_TIME TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (APPLICATION,HOST_IP)
);
COMMENT ON COLUMN SYS_SHEDLOCK_APP.APPLICATION IS '当前实例应用';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.HOST_IP IS '当前实例应用所属IP';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.HOST_NAME IS '创建机器';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.STATE IS '状态 0.关闭 1.开启';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.UPDATE_TIME IS '创建时间';
COMMENT ON TABLE  SYS_SHEDLOCK_APP IS '集群分佈式鎖-应用配置';

-- 定时任务锁(new)
CREATE TABLE SYS_SHEDLOCK_JOB (
  APPLICATION VARCHAR2(64) NOT NULL ,
  NAME VARCHAR2(64) not null,
  HOST_IP VARCHAR2(32) not null,
  LOCKED_AT timestamp(6) NOT NULL,
  LOCK_UNTIL timestamp(6) NOT NULL,
  LOCKED_BY VARCHAR2(100) NOT NULL,
  STATE CHAR(1) DEFAULT 1,
  DATA VARCHAR2(256),
  LABEL VARCHAR2(100),
  UPDATE_TIME TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (APPLICATION, NAME)
);
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.APPLICATION IS '当前实例应用';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.NAME IS '任務名稱(即ID)';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.HOST_IP IS '当前实例应用所属IP';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCKED_AT IS '任務開始鎖定';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCK_UNTIL IS '任務鎖定至';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCKED_BY IS '任務執行人';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LABEL IS '任務標識';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.STATE IS '0.close关闭 1.open开启(默认) 局部限制标志位(只限制所有相同实例中的此任务)';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.DATA IS 'job参数';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.UPDATE_TIME IS '最后更新时间(也即最近一次执行时间/获取锁时间)';
COMMENT ON TABLE  SYS_SHEDLOCK_JOB IS '集群分佈式鎖-任务配置';

