
-- 定时任务应用配置
DROP TABLE IF EXISTS SYS_SHEDLOCK_APP;
CREATE TABLE SYS_SHEDLOCK_APP (
  APPLICATION VARCHAR(64) NOT NULL ,
  HOST_IP VARCHAR(32) not null,
  HOST_NAME varchar(100),
  STATE CHAR(1) NOT NULL DEFAULT 1,
  LABEL VARCHAR(50),
  UPDATE_TIME TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (APPLICATION,HOST_IP)
);
COMMENT ON COLUMN SYS_SHEDLOCK_APP.APPLICATION IS '当前实例应用';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.HOST_IP IS '当前实例应用所属IP';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.HOST_NAME IS '创建机器';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.STATE IS '状态 0.关闭 1.开启';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.LABEL IS '备注信息';
COMMENT ON COLUMN SYS_SHEDLOCK_APP.UPDATE_TIME IS '创建及更新时间';
COMMENT ON TABLE  SYS_SHEDLOCK_APP IS '集群分佈式鎖-应用配置';

-- 定时任务锁(new)
DROP TABLE IF EXISTS SYS_SHEDLOCK_JOB;
CREATE TABLE SYS_SHEDLOCK_JOB (
  APPLICATION VARCHAR(64) NOT NULL ,
  NAME varchar(64) not null,
  HOST_IP varchar(32) not null,
  LOCKED_AT timestamp(6) NOT NULL,
  LOCK_UNTIL timestamp(6) NOT NULL,
  LOCKED_BY varchar(100) NOT NULL,
  STATE CHAR(1) NOT NULL DEFAULT 1,
  DATA VARCHAR(256),
  LABEL VARCHAR(50),
  CALL_TYPE VARCHAR(20),
  CALL_VALUE VARCHAR(100),
  UPDATE_TIME TIMESTAMP(3) NOT NULL,
  PRIMARY KEY (APPLICATION, NAME)
);
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.APPLICATION IS '应用';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.NAME IS '任务KEY';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.HOST_IP IS '当前实例应用所属IP';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCKED_AT IS '任務開始鎖定';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCK_UNTIL IS '任務鎖定至';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LOCKED_BY IS '任務執行人';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.STATE IS '0.close关闭 1.open开启(默认) 局部限制标志位(只限制所有相同实例中的此任务)';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.DATA IS 'job传入数据';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.LABEL IS '任务描述';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.CALL_TYPE IS '定时任务类型';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.CALL_VALUE IS '定时任务值';
COMMENT ON COLUMN SYS_SHEDLOCK_JOB.UPDATE_TIME IS '最后更新时间(也即最近一次执行时间/获取锁时间)';
COMMENT ON TABLE  SYS_SHEDLOCK_JOB IS '集群分佈式鎖-任务配置';


