
-- 定时任务应用配置
DROP TABLE IF EXISTS SYS_SHEDLOCK_APP;
CREATE TABLE SYS_SHEDLOCK_APP (
  APPLICATION VARCHAR(64) NOT NULL COMMENT '当前实例应用',
  HOST_IP VARCHAR(32) not null COMMENT '当前实例应用所属IP',
  HOST_NAME varchar(100) COMMENT '创建机器',
  STATE CHAR(1) NOT NULL DEFAULT 1 COMMENT '状态 0.关闭 1.开启',
  LABEL VARCHAR(50) COMMENT '备注信息',
  UPDATE_TIME TIMESTAMP(3) NOT NULL COMMENT '创建及更新时间',
  PRIMARY KEY (APPLICATION,HOST_IP)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='集群分佈式鎖-应用配置';

-- 定时任务锁(new)
DROP TABLE IF EXISTS SYS_SHEDLOCK_JOB;
CREATE TABLE SYS_SHEDLOCK_JOB (
  APPLICATION VARCHAR(64) NOT NULL COMMENT '当前实例应用',
  NAME varchar(64) not null COMMENT '任務名稱',
  HOST_IP varchar(32) not null COMMENT '当前实例应用所属IP',
  LOCKED_AT timestamp(6) NOT NULL COMMENT '任務開始鎖定',
  LOCK_UNTIL timestamp(6) NOT NULL COMMENT '任務鎖定至',
  LOCKED_BY varchar(100) NOT NULL COMMENT '任務執行人',
  STATE CHAR(1) NOT NULL DEFAULT 1 COMMENT '0.close关闭 1.open开启(默认) 具体是否关闭取决于lock_until',
  DATA VARCHAR(256)  COMMENT '任务数据',
  LABEL varchar(100) COMMENT '任务备注',
  CALL_TYPE VARCHAR(20),
  CALL_VALUE VARCHAR(100),
  UPDATE_TIME TIMESTAMP(3) NOT NULL COMMENT '创建及更新时间',
  PRIMARY KEY (APPLICATION, NAME)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='集群分佈式鎖-任务配置';


